@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package dev.burin.anvilextension.food;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;